BEGIN TRANSACTION;
CREATE TABLE "users" ("id" integer not null primary key autoincrement, "email" varchar not null, "password" varchar not null, "created_at" datetime not null, "updated_at" datetime not null);
INSERT INTO `users` VALUES ('1','cegrif01@gmail.com','$2y$10$IVoT3qwMznhPTwTwR1mxPO2DYgVQhxgIcYBAGIfRFlTUdE0HswPei','2015-01-25 19:26:24','2015-01-25 19:26:24');
INSERT INTO `users` VALUES ('2','test_email@gmail.com','$2y$10$jlQ4RmO0u1gXAwQwrmuE1OSF9qFcWzIvrrfeoF5onhn19WXBXjrVy','2015-01-25 19:26:24','2015-01-25 19:26:24');
CREATE TABLE "tasks" ("id" integer not null primary key autoincrement, "user_id" integer not null, "body" varchar not null, "created_at" datetime not null, "updated_at" datetime not null);
CREATE TABLE "roles" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text null, "created_at" datetime not null, "updated_at" datetime not null);
INSERT INTO `roles` VALUES ('1','saturday_tps_report_specialist',NULL,'2015-01-25 19:26:24','2015-01-25 19:26:24');
INSERT INTO `roles` VALUES ('2','sunday_tps_report_specialist',NULL,'2015-01-25 19:26:24','2015-01-25 19:26:24');
CREATE TABLE "roleables" ("id" integer not null primary key autoincrement, "role_id" integer not null, "caller_type" varchar not null, "caller_id" integer not null, foreign key("role_id") references "roles"("id"));
INSERT INTO `roleables` VALUES ('1','1','User','1');
INSERT INTO `roleables` VALUES ('2','2','User','2');
CREATE TABLE "permissions" ("id" integer not null primary key autoincrement, "type" varchar not null, "action" varchar not null, "resource_type" varchar null, "resource_id" integer null, "created_at" datetime not null, "updated_at" datetime not null);
INSERT INTO `permissions` VALUES ('1','privilege','workOnSaturday','tps_report_generator',NULL,'2015-01-25 19:26:24','2015-01-25 19:26:24');
INSERT INTO `permissions` VALUES ('2','privilege','workOnSunday','tps_report_generator',NULL,'2015-01-25 19:26:24','2015-01-25 19:26:24');
CREATE TABLE "permissionables" ("id" integer not null primary key autoincrement, "permission_id" integer not null, "caller_type" varchar not null, "caller_id" integer not null, foreign key("permission_id") references "permissions"("id"));
CREATE TABLE "permission_role" ("id" integer not null primary key autoincrement, "permission_id" integer not null, "role_id" integer not null, foreign key("permission_id") references "permissions"("id"), foreign key("role_id") references "roles"("id"));
INSERT INTO `permission_role` VALUES ('1','1','1');
INSERT INTO `permission_role` VALUES ('2','2','2');
CREATE TABLE "migrations" ("migration" varchar not null, "batch" integer not null);
INSERT INTO `migrations` VALUES ('2014_12_02_183619_create_users_table','1');
INSERT INTO `migrations` VALUES ('2014_12_02_183700_create_tasks_table','1');
INSERT INTO `migrations` VALUES ('2015_01_11_172842_create_roles_table','1');
INSERT INTO `migrations` VALUES ('2015_01_11_173520_create_permissions_table','1');
INSERT INTO `migrations` VALUES ('2015_01_11_173951_create_permission_role_table','1');
INSERT INTO `migrations` VALUES ('2015_01_11_180056_create_roleables_table','1');
INSERT INTO `migrations` VALUES ('2015_01_11_182252_create_permissionables_table','1');
CREATE INDEX users_password_index on "users" ("password");
CREATE INDEX users_email_index on "users" ("email");
CREATE INDEX tasks_user_id_index on "tasks" ("user_id");
CREATE INDEX roleables_role_id_index on "roleables" ("role_id");
CREATE INDEX roleables_caller_id_index on "roleables" ("caller_id");
CREATE INDEX permissionables_permission_id_index on "permissionables" ("permission_id");
CREATE INDEX permissionables_caller_id_index on "permissionables" ("caller_id");
CREATE INDEX permission_role_role_id_index on "permission_role" ("role_id");
CREATE INDEX permission_role_permission_id_index on "permission_role" ("permission_id");
COMMIT;
